CREATE DATABASE Compumundo; -- se crea la base de datos
USE Compumundo;

CREATE TABLE CLIENTES
(CLIENTE_ID INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR (100),
DIRECCION VARCHAR (255),
TELEFONO VARCHAR(15),
EMAIL VARCHAR (100));

CREATE TABLE PRODUCTOS
(PRODUCTO_ID INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR (100),
DESCRIPCION TEXT,
PRECIO DECIMAL (10, 2),
STOCK INT);

CREATE TABLE VENTAS
(VENTA_ID INT PRIMARY KEY auto_increment,
CLIENTE_ID INT,
FECHA DATE,
TOTAL DECIMAL (10, 2),
FOREIGN KEY VENTAS(CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID));

CREATE TABLE DETALLE_VENTAS
(DETALLE_ID INT PRIMARY KEY auto_increment,
VENTA_ID INT, --
PRODUCTO_ID INT, --
CANTIDAD INT,
SUBTOTAL DECIMAL (10, 2),
CONSTRAINT FK_VENTA FOREIGN KEY (VENTA_ID) REFERENCES VENTAS (VENTA_ID),
CONSTRAINT FK_PRODUCTOS FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (PRODUCTO_ID));

RENAME TABLE CLIENTES TO CLIENTES2;


